typography_spectrum: 0.27212616137560863
color:
  brandStrength: 0.7997909841299204
  lightness: 0.6402806917441511
  saturation: 0.06571095463727591
  rhythmicContrast: 0.677070353146329
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
github: true
layout_spectrum: 0.1619084732578422
author:
  name: Henrik Sidenius - Circles of Business
  email: hsi@circlesofbusiness.com
  url: www.circlesofbusiness.com
name: Lunch´n Learn - Vidensworkshops
url: 'https://thegrid.ai/Lunchnlearn/'
title: Lunchn learn - Vidensworkshops
content: []
description: >-
  Vi er lige nu i proces med, at finde eksperter på alle de mange emner, som vi
  mener du som leder eller ejer i små- og mellemstore virksomheder efterspørger
  mere viden om. Hjælp os godt på vej med at give dine forslag til hvilke emner
  du kunne tænke dig at få mere viden om?
purpose:
  - type: contact
    url: 'mailto:hsi@circlesofbusiness.com'
    label: 'Kontakt mig på: '
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/89a85bac-73c3-4d22-9ac3-f6a616865e86.jpg
