typography_spectrum: 0.27212616137560863
color:
  brandStrength: 0.7997909841299204
  lightness: 0.6402806917441511
  saturation: 0.06571095463727591
  rhythmicContrast: 0.677070353146329
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
github: true
layout_spectrum: 0.1619084732578422
author:
  name: Henrik Sidenius - Circles of Business
  email: hsi@circlesofbusiness.com
  url: www.circlesofbusiness.com
name: Lunch´n Learn - Vidensworkshops
url: 'https://thegrid.ai/Lunchnlearn/'
title: Lunchn learn
content: []
description: >-
  We are in the process of making auditions for business meetings with Top 200
  companies. In january we will be open for new business partners. who needs
  business meetings with Top 200 companies
purpose:
  - type: contact
    url: 'mailto:hsi@circlesofbusiness.com'
    label: Sign up
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/89a85bac-73c3-4d22-9ac3-f6a616865e86.jpg
