typography_spectrum: 0.27212616137560863
color:
  brandStrength: 0.7997909841299204
  lightness: 0.6402806917441511
  saturation: 0.06571095463727591
  rhythmicContrast: 0.677070353146329
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
github: true
layout_spectrum: 0.1619084732578422
author:
  name: Henrik Sidenius - Circles of Business
  email: hsi@circlesofbusiness.com
  url: www.circlesofbusiness.com
name: Lunch´n Learn - Vidensworkshops
url: 'https://thegrid.ai/Lunchnlearn/'
title: Lunchn learn - Vidensworkshops
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/93d1f70f-c94d-4831-8f31-5c3bc98538cc.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/93d1f70f-c94d-4831-8f31-5c3bc98538cc.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Vi er lige nu i proces med, at finde eksperter på alle de mange emner, som vi
  mener du som leder eller ejer i små- og mellemstore virksomheder efterspørger
  mere viden om. Hjælp os godt på vej med at give dine forslag til hvilke emner
  du kunne tænke dig at få mere viden om?
purpose:
  - type: contact
    url: 'mailto:hsi@circlesofbusiness.com'
    label: 'Kontakt mig på: '
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/89a85bac-73c3-4d22-9ac3-f6a616865e86.jpg
